/**
 * Backend error codes — mirrors ErrorCodes.cs exactly.
 *
 * Numbering scheme:
 * - 1000–1999: Validation & Value Object errors → HTTP 400
 * - 2000–2999: Authentication errors → HTTP 401
 * - 3000–3999: Authorization errors → HTTP 403
 * - 4000–4999: Entity not found → HTTP 404
 * - 5000–5999: Business rule violations → HTTP 409
 * - 6000–6999: Infrastructure errors → HTTP 500/502
 * - 9000–9999: Generic/unexpected errors → HTTP 500
 */
export const ERROR_CODES = {
  // ── Validation (1000–1999) ─────────────────────────────────────────────
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  INVALID_VALUE: 'INVALID_VALUE',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_COUNTRY_CODE: 'INVALID_COUNTRY_CODE',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  INVALID_WEBSITE_URL: 'INVALID_WEBSITE_URL',
  INVALID_TAX_ID: 'INVALID_TAX_ID',
  INVALID_LEGAL_NAME: 'INVALID_LEGAL_NAME',
  INVALID_COMMERCIAL_NAME: 'INVALID_COMMERCIAL_NAME',
  INVALID_SUPPLIER_ADDRESS: 'INVALID_SUPPLIER_ADDRESS',
  INVALID_ANNUAL_BILLING: 'INVALID_ANNUAL_BILLING',
  INVALID_SUPPLIER_ID: 'INVALID_SUPPLIER_ID',

  // ── Authentication (2000–2999) ─────────────────────────────────────────
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_PENDING_VERIFICATION: 'ACCOUNT_PENDING_VERIFICATION',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // ── Authorization (3000–3999) ──────────────────────────────────────────
  AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // ── Not Found (4000–4999) ──────────────────────────────────────────────
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  SCREENING_RESULT_NOT_FOUND: 'SCREENING_RESULT_NOT_FOUND',

  // ── Business Rule Violations (5000–5999) ──────────────────────────────
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  INVALID_OPERATION: 'INVALID_OPERATION',
  SUPPLIER_TAX_ID_ALREADY_EXISTS: 'SUPPLIER_TAX_ID_ALREADY_EXISTS',
  INVALID_SUPPLIER_STATE: 'INVALID_SUPPLIER_STATE',
  SUPPLIER_ALREADY_DELETED: 'SUPPLIER_ALREADY_DELETED',

  // ── Infrastructure (6000–6999) ─────────────────────────────────────────
  INFRASTRUCTURE_ERROR: 'INFRASTRUCTURE_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_INTEGRITY_VIOLATION: 'DATABASE_INTEGRITY_VIOLATION',
  REQUIRED_SEED_DATA_MISSING: 'REQUIRED_SEED_DATA_MISSING',

  // ── Rate Limiting (7000–7999) ──────────────────────────────────────────
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ── Generic (9000–9999) ────────────────────────────────────────────────
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export type ErrorCodeKey = keyof typeof ERROR_CODES;
